---
name: "Provision Security Groups"

on:
  workflow_call:
    inputs:
      namespace:
        description: "The deployment namespace (alias)"
        required: true
        type: string
      region:
        description: "The deployment region"
        type: string
        required: true
      tp_env:
        description: "The deployment environment"
        type: string
        required: true
      node_types:
        description: "The deployment node types"
        required: true
        type: string
      inventories_branch:
        description: "Override the inventory repository branch"
        required: true
        type: string
      state_branch:
        description: "Override the iaas-state-branch repository branch"
        required: true
        type: string
        default: "staging"
      ansible_debug:
        description: "Choose Ansible Debug Level"
        required: true
        default: '-v'
        type: string

    secrets:
      token:
        description: "The token to use"
        required: true
      ansible_vault_key:
        description: "The Ansible vault encryption key to use"
        required: true

jobs:
  dependencies_prep:
    name: Dependencies prep
    runs-on:
      - self-hosted
      - base-runner
    outputs:
      runner_env: ${{ steps.runner_env.outputs.major_env }}
    steps:
      - name: Checkout this repo
        id: checkout-workflows
        uses: actions/checkout@v5

      - name: Output the runner environment
        id: runner_env
        uses: Tvlport-IAAS/iaas-workflows/actions/iaas-major-env@main
        with:
          tp_env: ${{ inputs.tp_env }}

  build_deployment_module:
    name: Run build deployment module
    runs-on:
      - self-hosted
      - "${{ needs.dependencies_prep.outputs.runner_env }}"
      - onprem
      - toolkit
      - podman
    needs: dependencies_prep
    steps:
      - name: Checkout this repo
        id: checkout-workflows
        uses: actions/checkout@v5

      - name: Set deployment path
        id: set-deployment-path
        shell: bash
        run: |
          deployment_path="io/travelport/${{ inputs.tp_env }}/${{ inputs.region }}/${{ inputs.namespace }}"
          echo "deployment_path=${deployment_path}" >> $GITHUB_OUTPUT

      - name: Prepare IAAS ansible workspace
        id: workspace-prep
        uses: Tvlport-IAAS/iaas-workflows/actions/iaas-ansible-workspace@main
        with:
          deployment_path: "AnsibleInventories/${{ steps.set-deployment-path.outputs.deployment_path }}"
          node_types: "${{ inputs.node_types }}"
          inventories_branch: ${{ inputs.inventories_branch }}
          token: ${{ secrets.token }}
          ansible_vault_key: ${{ secrets.ansible_vault_key }}

      - name: Checkout iaas-app-state repo
        id: checkout-iaas-app-state
        uses: actions/checkout@v5
        with:
          repository: Tvlport-IAAS/iaas-app-state
          token: ${{ secrets.token }}
          path: terraform_working
          ref: ${{ inputs.state_branch }}

      - name: Run build deployment module
        uses: Tvlport-IAAS/iaas-workflows/actions/iaas-ansible-run@main
        with:
          inventory_path: "${{ steps.workspace-prep.outputs.inventory_path }}"
          node_types: "${{ inputs.node_types }}"
          playbook: "Pipelines/playbooks/customer/firewall_providers/FirewallCompleteRules.yml"
          ansible_debug: ${{ inputs.ansible_debug }}

      - name: Build commit message
        id: commit-message
        shell: bash
        run: |
          repo=$(echo "${{ github.repository }}" | cut -d '/' -f2)
          inventory_message="${repo}#${{ github.run_number }} - GIT push to ${{ inputs.inventories_branch }}"
          echo "inventory_message=${inventory_message}" >> $GITHUB_OUTPUT
          state_message="${repo}#${{ github.run_number }} - TF working push to staging"
          echo "state_message=${state_message}" >> $GITHUB_OUTPUT

      - name: Push changes to AnsibleInventories repo on ${{ inputs.inventories_branch }} branch
        id: push-iaas-inventories
        uses: Tvlport-IAAS/iaas-workflows/actions/iaas-git-push@main
        with:
          commit_message: "${{ steps.commit-message.outputs.inventory_message }}"
          path: ./AnsibleInventories
          file_patterns: "*.csv *_dbedit.txt"
          destination_branch: ${{ inputs.inventories_branch }}
          access_token: ${{ secrets.token }}
          force: true

      - name: Push changes to state repo on ${{ inputs.state_branch }} branch
        id: push-iaas-app-state
        uses: Tvlport-IAAS/iaas-workflows/actions/iaas-git-push@main
        with:
          commit_message: "${{ steps.commit-message.outputs.state_message }}"
          path: ./terraform_working
          destination_branch: ${{ inputs.state_branch }}
          access_token: ${{ secrets.token }}
          force: true

      - name: Cleanup private keys
        id: cleanup-keys
        uses: Tvlport-IAAS/iaas-workflows/actions/iaas-keys-cleanup@main
